from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

def create_report(name, age, condition, risk):

    doc = SimpleDocTemplate("report.pdf")
    styles = getSampleStyleSheet()

    # Custom title style
    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    content = []

    # ==============================
    # TITLE
    # ==============================
    content.append(Paragraph("CardioAI Pro – ECG Diagnostic Report", title_style))
    content.append(Spacer(1, 20))

    # ==============================
    # PATIENT DETAILS
    # ==============================
    content.append(Paragraph("<b>Patient Information</b>", styles["Heading2"]))
    content.append(Paragraph(f"Name: {name}", styles["Normal"]))
    content.append(Paragraph(f"Age: {age}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # ==============================
    # DIAGNOSIS
    # ==============================
    content.append(Paragraph("<b>Diagnosis</b>", styles["Heading2"]))
    content.append(Paragraph(f"Detected Condition: {condition}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # ==============================
    # RISK SCORE
    # ==============================
    content.append(Paragraph("<b>Risk Assessment</b>", styles["Heading2"]))
    content.append(Paragraph(f"Risk Score: {risk:.2f} / 100", styles["Normal"]))

    # Recommendation
    if risk > 75:
        recommendation = "Immediate medical attention is required."
    elif risk > 40:
        recommendation = "Regular monitoring is advised."
    else:
        recommendation = "Condition appears stable."

    content.append(Paragraph(f"Recommendation: {recommendation}", styles["Normal"]))
    content.append(Spacer(1, 20))

    # ==============================
    # FOOTER
    # ==============================
    content.append(Paragraph(
        "Generated by CardioAI Pro – AI-based ECG Monitoring System",
        styles["Italic"]
    ))

    doc.build(content)

    return "report.pdf"